[agent]
name = "unified-debug-agent"
version = "1.0.0"
description = "A unified debugging agent that handles complete debugging workflows from bug analysis to code fixes. Consolidates bug localization, code fixing, human review, and patch application into a single cost-effective agent with direct tool integration."

[options.DEEPSEEK_API_KEY]
type = "string"
description = "DeepSeek API Key for LLM operations"

[options.MODEL_NAME]
type = "string"
description = "What model to use"
default = "deepseek-chat"

[options.MODEL_PROVIDER]
type = "string"
description = "What model provider to use"
default = "openai"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.1"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "8000"

[options.MODEL_BASE_URL]
type = "string"
description = "Model API base URL"
default = "https://api.deepseek.com/v1"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

[options.QDRANT_API_KEY]
type = "string"
description = "Qdrant API Key for vector database access"

[options.QDRANT_URL]
type = "string"
description = "Qdrant database URL"

[options.CODESTRAL_API_KEY]
type = "string"
description = "Codestral API Key for code fix generation"

[runtimes.executable]
command = ["python3", "main.py"]

[runtimes.docker]
image = "coral-debug-agent:latest"